version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "superadmin"
      POSTGRES_DB: "users_security_db"
      POSTGRES_PASSWORD: "APqWgb9VL2e5IbE"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /c/example_volumes/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      apiaction:
        ipv4_address: 172.16.1.2

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "denis.filic@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "eerreerr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - /c/example_volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    links:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      apiaction:
        ipv4_address: 172.16.1.3

  ertelapiaction:
    container_name: ertelapiaction_container
    image: denisfilichev/ertelapiaction:latest
    volumes:
      - /c/example_volumes:/app/sert
      - /c/example_volumes/conf:/app/conf
    ports:
      - "10000:10000"
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      apiaction:
        ipv4_address: 172.16.1.4

networks:
  apiaction:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
